'use strict';
const $=id=>document.getElementById(id), key='reading-journey-v1', fmt=new Intl.NumberFormat('ar-SA',{maximumFractionDigits:1});
const n=v=>fmt.format(v), today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}, dateAt=(i)=>{const d=new Date(state.start+'T12:00:00');d.setDate(d.getDate()+i);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
let state={start:today(),selected:0,books:Array.from({length:21},()=>({title:'',author:'',total:0})),sessions:[],timer:null};
try{const stored=JSON.parse(localStorage.getItem(key));if(stored&&Array.isArray(stored.books)&&stored.books.length===21&&Array.isArray(stored.sessions))state=stored}catch(e){$('storage').textContent='تعذّر استعادة البيانات؛ تحقق من سماح المتصفح بالتخزين.'}
let noticeTimer, timed=false;
function notice(s){$('notice').textContent=s;$('notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').hidden=true,4500)}
function save(){try{localStorage.setItem(key,JSON.stringify(state));return true}catch(e){$('storage').textContent='تعذّر الحفظ في المتصفح. لا تغلق الصفحة حتى يتاح التخزين.';notice('تعذّر حفظ البيانات في المتصفح');return false}}
const sessionsFor=i=>state.sessions.filter(s=>s.book===i), pagesFor=i=>sessionsFor(i).reduce((a,s)=>a+s.pages,0), seconds=()=>state.timer?state.timer.elapsed+(state.timer.running?Math.max(0,Date.now()-state.timer.since)/1000:0):0;
function render(){
const b=state.books[state.selected], read=pagesFor(state.selected), ss=state.sessions, pages=ss.reduce((a,s)=>a+s.pages,0), secs=ss.reduce((a,s)=>a+s.seconds,0), complete=state.books.filter((b,i)=>b.total>0&&pagesFor(i)>=b.total).length, percent=state.books.reduce((a,b,i)=>a+(b.total?Math.min(1,pagesFor(i)/b.total):0),0)/21*100;
$('completion').textContent=n(percent)+'٪';$('completed').textContent=`${n(complete)} من ٢١ كتابًا مكتملًا`;$('totalbar').style.width=percent+'%';$('pages').textContent=n(pages);$('remaining').textContent=`${n(state.books.reduce((a,b,i)=>a+Math.max(0,b.total-pagesFor(i)),0))} صفحة متبقية في الكتب المضافة`;$('time').textContent=secs>=3600?n(secs/3600)+' س':n(secs/60)+' د';$('sessions').textContent=`${n(ss.length)} جلسة مسجلة`;$('speed').textContent=secs?n(pages/(secs/3600)):'—';
const sorted=[...ss].sort((a,b)=>a.date.localeCompare(b.date)||a.created-b.created);if(ss.length>1){let first=sorted[0],last=sorted.at(-1),g=(last.pages/last.seconds/(first.pages/first.seconds)-1)*100;$('growth').textContent=(g>0?'+':'')+n(g)+'٪';$('growthNote').textContent='سرعة آخر جلسة مقارنة بأول جلسة'}else{$('growth').textContent='—';$('growthNote').textContent='يظهر بعد تسجيل جلستين'}
$('start').value=state.start;$('days').replaceChildren();state.books.forEach((book,i)=>{let btn=document.createElement('button');btn.className='day'+(i===state.selected?' active':'')+(book.total&&pagesFor(i)>=book.total?' done':'');btn.textContent=n(i+1);btn.setAttribute('aria-label',`اليوم ${i+1}: ${book.title||'لم يضف كتاب'}`);btn.setAttribute('aria-pressed',String(i===state.selected));btn.onclick=()=>{state.selected=i;save();render()};$('days').append(btn)});
$('dayTitle').textContent=`كتاب اليوم ${n(state.selected+1)}`;$('bookDate').textContent=new Date(dateAt(state.selected)+'T12:00:00').toLocaleDateString('ar-SA',{calendar:'gregory',weekday:'long',month:'long',day:'numeric'});$('title').value=b.title;$('author').value=b.author;$('total').value=b.total||'';$('bookStatus').textContent=b.total&&read>=b.total?'مكتمل':read?'قيد القراءة':'لم يبدأ';$('bookProgress').textContent=`${n(read)} من ${n(b.total)} صفحة`;$('bookPercent').textContent=n(b.total?read/b.total*100:0)+'٪';$('bookbar').style.width=(b.total?Math.min(100,read/b.total*100):0)+'%';
let bookSecs=sessionsFor(state.selected).reduce((a,s)=>a+s.seconds,0);$('estimate').textContent=b.total&&read>=b.total?'أتممت هذا الكتاب. أحسنت!':read?`المتبقي ${n(b.total-read)} صفحة · الوقت المتوقع ${n((b.total-read)*bookSecs/read/60)} دقيقة وفق سرعتك في هذا الكتاب.`:'سجّل جلسة لعرض الوقت المتوقع لإنهاء الكتاب.';
$('timerBook').textContent=state.timer?state.books[state.timer.book].title:b.title||'احفظ كتابك ثم ابدأ المؤقّت';$('play').textContent=state.timer?.running?'إيقاف مؤقّت':state.timer?'استئناف القراءة':'ابدأ القراءة';$('play').disabled=!state.timer&&(!b.total||read>=b.total);$('finish').disabled=!state.timer;$('manual').disabled=!b.total||read>=b.total;
$('chart').replaceChildren();let values=Array.from({length:21},(_,i)=>ss.filter(s=>s.date===dateAt(i)).reduce((a,s)=>a+s.pages,0)), max=Math.max(1,...values);values.forEach((v,i)=>{let col=document.createElement('div');col.className='column';col.title=`اليوم ${n(i+1)}: ${n(v)} صفحة`;let bar=document.createElement('i');bar.style.height=(v/max*110)+'px';let label=document.createElement('small');label.textContent=n(i+1);col.append(bar,label);$('chart').append(col)});$('chart').setAttribute('aria-label',values.map((v,i)=>`اليوم ${i+1}: ${v} صفحة`).join('، '));let outside=ss.filter(s=>s.date<state.start||s.date>dateAt(20)).length;$('chartNote').textContent=ss.length?(outside?`${n(outside)} جلسة خارج فترة البرنامج؛ محسوبة في الملخص والسجل.`:'كل جلسة تضيف خطوة إلى رحلتك.'):'ستظهر قراءاتك هنا بعد أول جلسة.';
$('history').replaceChildren();if(!ss.length){let el=document.createElement('p');el.className='empty';el.textContent='لا توجد جلسات بعد. احفظ كتابًا وابدأ القراءة.';$('history').append(el)}else{let table=document.createElement('table');let head=document.createElement('thead');head.innerHTML='<tr><th>الكتاب والتاريخ</th><th>الصفحات</th><th>الدقائق</th><th>صفحة/ساعة</th><th>إجراء</th></tr>';table.append(head);let body=document.createElement('tbody');[...sorted].reverse().forEach(s=>{let row=document.createElement('tr');[state.books[s.book].title+' · '+s.date,n(s.pages),n(s.seconds/60),n(s.pages/s.seconds*3600)].forEach(v=>{let cell=document.createElement('td');cell.textContent=v;row.append(cell)});let cell=document.createElement('td'),btn=document.createElement('button');btn.className='secondary';btn.textContent='حذف';btn.setAttribute('aria-label','حذف جلسة '+state.books[s.book].title+' '+s.date);btn.onclick=()=>{if(confirm('حذف هذه الجلسة وتحديث إجمالي القراءة؟')){state.sessions=state.sessions.filter(x=>x.id!==s.id);save();render()}};cell.append(btn);row.append(cell);body.append(row)});table.append(body);$('history').append(table)}updateClock();}
function updateClock(){let s=Math.floor(seconds());$('clock').textContent=[Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(x=>String(x).padStart(2,'0')).join(':')}
$('bookForm').onsubmit=e=>{e.preventDefault();let total=Number($('total').value),title=$('title').value.trim();if(!title||!Number.isInteger(total)||total<1||total>100000)return notice('أدخل عنوانًا وعدد صفحات صحيحًا');if(total<pagesFor(state.selected))return notice('عدد الصفحات أقل من الصفحات المسجلة. صحّح الجلسات أولًا.');state.books[state.selected]={title,author:$('author').value.trim(),total};save();render();notice('تم حفظ بيانات الكتاب')};
$('start').onchange=()=>{if(!$('start').value)return;state.start=$('start').value;save();render()};
$('play').onclick=()=>{if(!state.timer)state.timer={book:state.selected,elapsed:0,since:Date.now(),running:true};else if(state.timer.running){state.timer.elapsed=seconds();state.timer.running=false}else{state.timer.since=Date.now();state.timer.running=true}save();render()};
function openSession(isTimed){timed=isTimed;let i=isTimed?state.timer.book:state.selected;if(isTimed&&state.timer.running){state.timer.elapsed=seconds();state.timer.running=false;save();render()}$('sessionBook').textContent=state.books[i].title+` · متبقٍ ${n(state.books[i].total-pagesFor(i))} صفحة`;$('sessionPages').value='';$('sessionPages').max=state.books[i].total-pagesFor(i);$('sessionMinutes').value=isTimed?Math.max(.01,Math.round(seconds()/60*100)/100):'';$('sessionDate').value=today();$('sessionDate').max=today();$('sessionError').textContent='';$('sessionDialog').showModal()}
$('manual').onclick=()=>openSession(false);$('finish').onclick=()=>openSession(true);$('cancel').onclick=()=>$('sessionDialog').close();
$('sessionForm').onsubmit=e=>{e.preventDefault();const i=timed?state.timer.book:state.selected,pages=Number($('sessionPages').value),minutes=Number($('sessionMinutes').value),date=$('sessionDate').value;if(!Number.isInteger(pages)||pages<1||pages>state.books[i].total-pagesFor(i)||!Number.isFinite(minutes)||minutes<=0||minutes>100000||!date||date>today()){$('sessionError').textContent='تحقق من الصفحات والمدة والتاريخ؛ لا يمكن تجاوز صفحات الكتاب.';return}state.sessions.push({id:crypto.randomUUID(),book:i,pages,seconds:minutes*60,date,created:Date.now()});if(timed)state.timer=null;save();$('sessionDialog').close();render();notice('تم تسجيل الجلسة وتحديث تقدمك')};
window.addEventListener('storage',e=>{if(e.key===key&&e.newValue){try{state=JSON.parse(e.newValue);render()}catch{}}});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'get_reading_progress',title:'عرض تقدم القراءة',description:'Read the recorded books and session totals in this browser without changes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No arguments accepted');return {start:state.start,books:state.books.map((b,i)=>({...b,day:i+1,pagesRead:pagesFor(i)})),sessionCount:state.sessions.length}}})).catch(()=>{})}catch{}}
render();setInterval(updateClock,1000);
