'use strict';
const $=id=>document.getElementById(id),key='reading-journey-v1',fmt=new Intl.NumberFormat('ar-SA',{maximumFractionDigits:1}),n=v=>fmt.format(v);
function dateString(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
const today=()=>dateString(new Date()),addDays=(s,n)=>{const d=new Date(s+'T12:00:00');d.setDate(d.getDate()+n);return dateString(d)};
let state={start:today(),end:addDays(today(),20),weekdays:[0,1,2,3,4,5,6],selected:0,books:[],sessions:[],timer:null},currentView='home',editing=-1,noticeTimer,finishWasRunning=false;
function notice(s){$('notice').textContent=s;$('notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').hidden=true,4500)}
function migrate(s){if(!s||!Array.isArray(s.books)||!Array.isArray(s.sessions))throw Error('Invalid state');s.end=s.end||addDays(s.start,20);s.weekdays=Array.isArray(s.weekdays)?s.weekdays:[0,1,2,3,4,5,6];s.selected=Math.max(0,Math.min(s.selected||0,Math.max(0,s.books.length-1)));return s}
try{const stored=JSON.parse(localStorage.getItem(key));if(stored)state=migrate(stored)}catch{setTimeout(()=>notice('تعذّر استعادة البيانات المحفوظة'),0)}
function save(){try{localStorage.setItem(key,JSON.stringify(state));return true}catch{notice('تعذّر حفظ البيانات في المتصفح');return false}}
function readingDates(start=state.start,end=state.end,days=state.weekdays,mode=state.scheduleMode,specific=state.specificDates){if(mode==='specific')return [...new Set(specific||[])].filter(d=>d>=start&&d<=end).sort();const result=[];if(!start||!end||start>end)return result;for(let d=new Date(start+'T12:00:00');dateString(d)<=end;d.setDate(d.getDate()+1)){if(days.includes(d.getDay()))result.push(dateString(d));if(result.length>3660)break}return result}
const sessionsFor=i=>state.sessions.filter(s=>s.book===i),pagesFor=i=>sessionsFor(i).reduce((a,s)=>a+s.pages,0),seconds=()=>state.timer?state.timer.elapsed+(state.timer.running?Math.max(0,Date.now()-state.timer.since)/1000:0):0;
function activeIndex(){if(state.timer)return state.timer.book;const selected=state.books[state.selected];if(selected?.total&&pagesFor(state.selected)<selected.total)return state.selected;const i=state.books.findIndex((b,j)=>b.total&&pagesFor(j)<b.total);return i>=0?i:state.books.length?0:-1}
function tick(){const s=Math.floor(seconds()),text=[Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(x=>String(x).padStart(2,'0')).join(':');$('clock').textContent=text;$('miniClock').textContent=text}
const titles={home:'الرئيسية',books:'كتبي',reader:'جلستي',progress:'تقدمي'};
function go(view,focus=true){currentView=titles[view]?view:'home';document.querySelectorAll('.app-view').forEach(e=>e.hidden=e.id!=='view-'+currentView);document.querySelectorAll('[data-view]').forEach(e=>{if(e.dataset.view===currentView)e.setAttribute('aria-current','page');else e.removeAttribute('aria-current')});$('screenTitle').textContent=titles[currentView];history.replaceState(null,'','#'+currentView);render();if(focus){window.scrollTo(0,0);$('screenTitle').focus({preventScroll:true})}}
function render(){const ss=state.sessions,pages=ss.reduce((a,s)=>a+s.pages,0),secs=ss.reduce((a,s)=>a+s.seconds,0),count=state.books.length,completed=state.books.filter((b,i)=>b.total&&pagesFor(i)>=b.total).length,percent=count?state.books.reduce((a,b,i)=>a+(b.total?Math.min(1,pagesFor(i)/b.total):0),0)/count*100:0;
$('completion').textContent=n(percent)+'٪';$('completed').textContent=`${n(completed)} من ${n(count)} كتاب مكتمل`;$('totalbar').style.width=percent+'%';$('pages').textContent=n(pages);$('remaining').textContent=`${n(state.books.reduce((a,b,i)=>a+Math.max(0,b.total-pagesFor(i)),0))} صفحة متبقية`;$('time').textContent=secs>=3600?n(secs/3600)+' س':n(secs/60)+' د';$('sessions').textContent=`${n(ss.length)} جلسة`;$('speed').textContent=secs?n(pages/secs*60):'—';const sorted=[...ss].sort((a,b)=>a.date.localeCompare(b.date)||a.created-b.created);if(sorted.length>1){const f=sorted[0],l=sorted.at(-1),g=(l.pages/l.seconds/(f.pages/f.seconds)-1)*100;$('growth').textContent=(g>0?'+':'')+n(g)+'٪';$('growthNote').textContent='آخر جلسة مقارنة بأول جلسة'}else{$('growth').textContent='—';$('growthNote').textContent='يظهر بعد جلستين'}
const dates=readingDates(),idx=activeIndex(),b=state.books[idx],read=idx>=0?pagesFor(idx):0;$('todayLabel').textContent=dates.includes(today())?'يوم قراءة': 'كتابي الحالي';$('todayBook').textContent=b?.title||'أضف كتابك الأول';$('todayAuthor').textContent=b?.author||'';$('todayProgress').textContent=b?.total?`${n(read)} من ${n(b.total)} صفحة`:'';$('todayBar').style.width=(b?.total?Math.min(100,read/b.total*100):0)+'%';$('todayRead').textContent=state.timer?'متابعة الجلسة':b?.total?'ابدأ القراءة':'إضافة كتاب';$('todayEdit').hidden=!b;
$('bookCount').textContent='('+n(count)+')';$('bookList').replaceChildren();if(!count){const p=document.createElement('p');p.className='muted';p.textContent='لم تُضف كتبًا بعد.';$('bookList').append(p)}state.books.forEach((book,i)=>{const btn=document.createElement('button');btn.className='book-tile';const title=document.createElement('strong');title.textContent=book.title||'كتاب بدون عنوان';const author=document.createElement('small');author.textContent=book.author||'';const status=document.createElement('small');const read=pagesFor(i);status.textContent=book.total?(read>=book.total?'مكتمل':`${n(read)} / ${n(book.total)} صفحة`):'أضف بيانات الكتاب';const bar=document.createElement('div');bar.className='bar';const fill=document.createElement('span');fill.style.width=(book.total?Math.min(100,read/book.total*100):0)+'%';bar.append(fill);btn.append(title,author,status,bar);btn.onclick=()=>editBook(i);$('bookList').append(btn)});
const sel=state.timer?state.timer.book:state.selected,book=state.books[sel];$('readerSelect').replaceChildren();state.books.forEach((b,i)=>{if(b.total){const op=document.createElement('option');op.value=i;op.textContent=b.title+(pagesFor(i)>=b.total?' — مكتمل':'');$('readerSelect').append(op)}});if(!$('readerSelect').options.length){const op=document.createElement('option');op.value='';op.textContent='أضف كتابًا من كتبي';$('readerSelect').append(op)}$('readerSelect').value=String(sel);$('readerSelect').disabled=!!state.timer;$('timerBook').textContent=book?.title||'لا يوجد كتاب مختار';$('play').textContent=!state.timer?'ابدأ القراءة':state.timer.running?'إيقاف':'استئناف';$('play').disabled=!state.timer&&(!book?.total||pagesFor(sel)>=book.total);$('finish').hidden=!state.timer;$('finish').disabled=!state.timer;$('miniTimer').hidden=!state.timer||currentView==='reader';if(state.timer){$('miniBook').textContent=state.books[state.timer.book].title;$('miniPause').textContent=state.timer.running?'إيقاف':'استئناف'}
$('chart').replaceChildren();const values=dates.map(d=>ss.filter(s=>s.date===d).reduce((a,s)=>a+s.pages,0)),max=Math.max(1,...values);values.forEach((v,i)=>{const col=document.createElement('div');col.className='column';col.title=`${dates[i]}: ${n(v)} صفحة`;const bar=document.createElement('i');bar.style.height=v/max*110+'px';const label=document.createElement('small');label.textContent=n(i+1);col.append(bar,label);$('chart').append(col)});$('chart').setAttribute('aria-label',dates.map((d,i)=>`${d}: ${values[i]} صفحة`).join('، ')||'لم تحدد أيام قراءة');const outside=ss.filter(s=>!dates.includes(s.date)).length;$('chartNote').textContent=!dates.length?'حدد خطة القراءة من كتبي.':outside?`${n(outside)} جلسة خارج أيام الخطة، محسوبة في الإجماليات.`:!ss.length?'لا توجد جلسات بعد.':'';
$('history').replaceChildren();if(!ss.length){const p=document.createElement('p');p.className='empty';p.textContent='لا توجد جلسات بعد.';$('history').append(p)}else{const table=document.createElement('table');table.innerHTML='<thead><tr><th>الكتاب والتاريخ</th><th>الصفحات</th><th>الدقائق</th><th>صفحة/دقيقة</th><th></th></tr></thead>';const tbody=document.createElement('tbody');sorted.reverse().forEach(s=>{const tr=document.createElement('tr');[state.books[s.book]?.title+' · '+s.date,n(s.pages),n(s.seconds/60),n(s.pages/s.seconds*60)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});const td=document.createElement('td'),btn=document.createElement('button');btn.className='secondary';btn.textContent='حذف';btn.onclick=()=>{if(confirm('حذف هذه الجلسة؟')){state.sessions=state.sessions.filter(x=>x.id!==s.id);save();render()}};td.append(btn);tr.append(td);tbody.append(tr)});table.append(tbody);$('history').append(table)}tick()}
function editBook(i){editing=i;const b=state.books[i];$('title').value=b?.title||'';$('author').value=b?.author||'';$('total').value=b?.total||'';$('bookDetail').textContent=b?.total?`${n(pagesFor(i))} من ${n(b.total)} صفحة`:'';$('readBook').hidden=!b?.total;$('readBook').disabled=!!state.timer||!!b?.total&&pagesFor(i)>=b.total;$('deleteBook').hidden=!b;$('deleteBook').disabled=state.timer?.book===i;$('bookDialog').showModal()}
$('bookForm').onsubmit=e=>{e.preventDefault();const title=$('title').value.trim(),total=Number($('total').value);if(!title||!Number.isInteger(total)||total<1||total>100000)return notice('أدخل عنوانًا وعدد صفحات صحيحًا');if(editing>=0&&total<pagesFor(editing))return notice('لا يمكن أن تقل صفحات الكتاب عن الصفحات المقروءة');const b={title,author:$('author').value.trim(),total};if(editing<0){state.books.push(b);state.selected=state.books.length-1}else{state.books[editing]=b;state.selected=editing}save();$('bookDialog').close();render()};
$('addBook').onclick=()=>editBook(-1);$('closeBook').onclick=()=>$('bookDialog').close();$('deleteBook').onclick=()=>{const i=editing;if(i<0||state.timer?.book===i)return;const has=sessionsFor(i).length;if(!confirm(has?'حذف الكتاب وجميع جلساته؟ سيتغير إجمالي الإنجاز.':'حذف هذا الكتاب؟'))return;state.books.splice(i,1);state.sessions=state.sessions.filter(s=>s.book!==i).map(s=>({...s,book:s.book>i?s.book-1:s.book}));if(state.timer&&state.timer.book>i)state.timer.book--;state.selected=Math.max(0,Math.min(state.selected>i?state.selected-1:state.selected,state.books.length-1));save();$('bookDialog').close();render()};$('readBook').onclick=()=>{if(editing<0||state.timer)return;state.selected=editing;save();$('bookDialog').close();go('reader')};
$('readerSelect').onchange=()=>{if(!state.timer&&$('readerSelect').value!==''){state.selected=Number($('readerSelect').value);save();render()}};
$('play').onclick=()=>{if(!state.timer){const b=state.books[state.selected];if(!b?.total||pagesFor(state.selected)>=b.total)return;state.timer={book:state.selected,elapsed:0,since:Date.now(),running:true}}else if(state.timer.running){state.timer.elapsed=seconds();state.timer.running=false}else{state.timer.since=Date.now();state.timer.running=true}save();render()};
$('finish').onclick=()=>{if(!state.timer)return;finishWasRunning=state.timer.running;state.timer.elapsed=seconds();state.timer.running=false;save();const i=state.timer.book;$('sessionBook').textContent=state.books[i].title;$('sessionPages').value='';$('sessionPages').max=state.books[i].total-pagesFor(i);$('sessionMinutes').value=Math.max(.01,Math.round(seconds()/60*100)/100);$('sessionDate').value=today();$('sessionDate').max=today();$('sessionError').textContent='';render();$('sessionDialog').showModal()};
function cancelFinish(){if(state.timer&&finishWasRunning){state.timer.since=Date.now();state.timer.running=true;save();render()}finishWasRunning=false}
$('cancel').onclick=()=>{$('sessionDialog').close();cancelFinish()};$('sessionDialog').addEventListener('cancel',cancelFinish);
$('sessionForm').onsubmit=e=>{e.preventDefault();if(!state.timer)return;const i=state.timer.book,pages=Number($('sessionPages').value),minutes=Number($('sessionMinutes').value),date=$('sessionDate').value;if(!Number.isInteger(pages)||pages<1||pages>state.books[i].total-pagesFor(i)||!Number.isFinite(minutes)||minutes<=0||minutes>100000||!date||date>today()){$('sessionError').textContent='تحقق من الصفحات والمدة والتاريخ.';return}state.sessions.push({id:crypto.randomUUID(),book:i,pages,seconds:minutes*60,date,created:Date.now()});state.timer=null;finishWasRunning=false;save();$('sessionDialog').close();render();notice('تم إنهاء الجلسة وتسجيلها')};
const weekdayNames=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];weekdayNames.forEach((name,i)=>{const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=i;input.checked=state.weekdays.includes(i);label.append(input,document.createTextNode(name));$('weekdays').append(label)});$('start').value=state.start;$('end').value=state.end;
let draftMode=state.scheduleMode||'weekly',draftDates=[...(state.specificDates||[])],calendarTarget='start',calendarMonth=state.start.slice(0,7);
const displayDate=d=>new Date(d+'T12:00:00').toLocaleDateString('ar-SA',{calendar:'gregory',day:'numeric',month:'long',year:'numeric'});
function planValues(){return{start:$('start').value,end:$('end').value,days:[...$('weekdays').querySelectorAll('input:checked')].map(e=>Number(e.value))}}
function previewPlan(){const p=planValues();draftDates=draftDates.filter(d=>d>=p.start&&d<=p.end);const invalid=!p.start||!p.end||p.start>p.end||(draftMode==='weekly'&&!p.days.length);$('planError').textContent=p.start>p.end?'نهاية الدورة يجب أن تكون بعد البداية أو في اليوم نفسه.':draftMode==='weekly'&&!p.days.length?'اختر يومًا واحدًا على الأقل.':'';const dates=invalid?[]:readingDates(p.start,p.end,p.days,draftMode,draftDates);$('readingCount').textContent=n(dates.length);$('planCount').textContent='';$('startDisplay').textContent=displayDate(p.start);$('endDisplay').textContent=displayDate(p.end);$('weeklyFields').hidden=draftMode!=='weekly';$('specificFields').hidden=draftMode!=='specific';$('weeklyMode').setAttribute('aria-pressed',String(draftMode==='weekly'));$('specificMode').setAttribute('aria-pressed',String(draftMode==='specific'));$('selectedDates').replaceChildren();draftDates.sort().forEach(d=>{const btn=document.createElement('button');btn.type='button';btn.className='date-chip';btn.textContent=displayDate(d)+' ×';btn.setAttribute('aria-label','إزالة '+displayDate(d));btn.onclick=()=>{draftDates=draftDates.filter(x=>x!==d);previewPlan()};$('selectedDates').append(btn)});return !invalid&&dates.length>0}
$('planForm').onchange=previewPlan;$('planForm').onsubmit=e=>{e.preventDefault();if(!previewPlan())return notice('اختر يوم قراءة واحدًا على الأقل ضمن الدورة');const p=planValues();state.start=p.start;state.end=p.end;state.weekdays=p.days;state.scheduleMode=draftMode;state.specificDates=[...draftDates];save();render();notice('تم حفظ خطة القراءة')};
$('weeklyMode').onclick=()=>{draftMode='weekly';previewPlan()};$('specificMode').onclick=()=>{draftMode='specific';previewPlan()};
function openCalendar(target){calendarTarget=target;calendarMonth=(target==='specific'?$('start').value:$(target).value).slice(0,7);drawCalendar();$('calendarDialog').showModal()}
function drawCalendar(){const first=new Date(calendarMonth+'-01T12:00:00'),year=first.getFullYear(),month=first.getMonth(),last=new Date(year,month+1,0).getDate();$('calendarTitle').textContent=calendarTarget==='specific'?'اختر أيام القراءة':calendarTarget==='start'?'بداية الدورة':'نهاية الدورة';$('calendarMonth').textContent=first.toLocaleDateString('ar-SA',{calendar:'gregory',year:'numeric',month:'long'});$('calendarGrid').replaceChildren();for(let i=0;i<first.getDay();i++)$('calendarGrid').append(document.createElement('span'));for(let day=1;day<=last;day++){const d=dateString(new Date(year,month,day,12)),btn=document.createElement('button');btn.type='button';btn.textContent=n(day);btn.setAttribute('aria-label',displayDate(d));btn.dataset.date=d;const selected=calendarTarget==='specific'?draftDates.includes(d):$(calendarTarget).value===d;btn.setAttribute('aria-pressed',String(selected));if(d===today())btn.classList.add('is-today');btn.disabled=calendarTarget==='specific'&&(d<$('start').value||d>$('end').value)||calendarTarget==='end'&&d<$('start').value;btn.onclick=()=>{if(calendarTarget==='specific'){draftDates=draftDates.includes(d)?draftDates.filter(x=>x!==d):[...draftDates,d];previewPlan();drawCalendar()}else{$(calendarTarget).value=d;if(calendarTarget==='start'&&$('end').value<d)$('end').value=d;previewPlan();$('calendarDialog').close()}};$('calendarGrid').append(btn)}$('calendarCount').textContent=calendarTarget==='specific'?n(draftDates.length)+' يوم محدد':'اختر التاريخ من التقويم';}
function shiftMonth(delta){const d=new Date(calendarMonth+'-01T12:00:00');d.setMonth(d.getMonth()+delta);calendarMonth=dateString(d).slice(0,7);drawCalendar()}
$('startPicker').onclick=()=>openCalendar('start');$('endPicker').onclick=()=>openCalendar('end');$('specificPicker').onclick=()=>openCalendar('specific');$('prevMonth').onclick=()=>shiftMonth(-1);$('nextMonth').onclick=()=>shiftMonth(1);$('closeCalendar').onclick=()=>$('calendarDialog').close();$('doneCalendar').onclick=()=>$('calendarDialog').close();
$('todayEdit').onclick=()=>editBook(activeIndex());$('todayRead').onclick=()=>{const i=activeIndex();if(state.timer){go('reader');return}if(i<0||!state.books[i]?.total){editBook(i);return}state.selected=i;save();go('reader')};$('miniOpen').onclick=()=>go('reader');$('miniPause').onclick=()=>$('play').click();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));window.addEventListener('hashchange',()=>go(location.hash.slice(1)));window.addEventListener('storage',e=>{if(e.key===key&&e.newValue){try{state=migrate(JSON.parse(e.newValue));render()}catch{}}});
const home=$('view-home');home.insertBefore(home.querySelector('.today-card'),home.querySelector('.overview'));previewPlan();go(location.hash.slice(1)||'home',false);setInterval(tick,1000);
