'use strict';
(()=>{
const tests=[
{title:'حديقة بين البيوت',text:`لاحظ سكان الحي أن قطعة الأرض الواقعة بين بيوتهم بقيت مهملة سنوات طويلة. كانت تمتلئ بالغبار في الصيف، وتتجمع فيها مياه المطر شتاءً. اقترحت نورة تحويلها إلى حديقة صغيرة، لكن بعض الجيران خشوا أن تتطلب عناية يومية لا يستطيعون الالتزام بها. لذلك اتفق الجميع على تجربة محدودة قبل اتخاذ قرار دائم.
بدأ الفريق بتنظيف نصف المساحة فقط. اختاروا نباتات محلية تتحمل الحرارة وتحتاج إلى ماء قليل، وتركوا ممرًا واسعًا يسمح لكبار السن بالحركة بسهولة. لم يشتروا مقاعد جديدة؛ بل أصلح نجار من الحي مقاعد قديمة تبرع بها أحد السكان. أما الأطفال فشاركوا في رسم لوحات صغيرة تحمل أسماء النباتات.
وضع المتطوعون جدولًا أسبوعيًا لتوزيع مهام الري والتنظيف. وفي نهاية كل أسبوع كانوا يسجلون كمية الماء المستخدمة، وعدد النباتات التي احتاجت إلى عناية إضافية. بعد شهر لاحظوا أن بعض الأحواض تتلقى شمسًا أكثر من غيرها، فنقلوا النباتات الحساسة إلى مكان أكثر ظلًا بدلًا من زيادة الري في الحديقة كلها.
بعد ثلاثة أشهر اجتمع الجيران لتقييم التجربة. لم تكن جميع النباتات قد نجحت، لكن المكان أصبح نقطة لقاء منتظمة، وتراجعت النفايات فيه. قرر السكان تطوير الجزء المتبقي تدريجيًا، مستفيدين من الأخطاء الأولى. تعلموا أن نجاح المشروع لم يعتمد على كثرة المال، بل على توزيع المسؤوليات ومراقبة النتائج وإجراء تعديلات صغيرة في الوقت المناسب.`,questions:[{q:'لماذا بدأ السكان بنصف المساحة؟',options:['لتجربة الفكرة قبل التوسع','لبناء متجر في الباقي','لمنع الأطفال من الدخول'],answer:0},{q:'كيف حصلوا على المقاعد؟',options:['استأجروها','أصلحوا مقاعد متبرعًا بها','اشتروها جديدة'],answer:1},{q:'ما التصرف عند تضرر النباتات من الشمس؟',options:['زيادة ري الحديقة كلها','إزالة كل الأحواض','نقل النباتات الحساسة إلى الظل'],answer:2}]},
{title:'رحلة كتاب',text:`كان سامي يدير مكتبة صغيرة قرب محطة الحافلات. لاحظ أن كثيرًا من الزوار يسألون عن الكتب ثم يغادرون دون شراء، لأنهم لا يعرفون إن كانت تناسب اهتماماتهم. بدلًا من توسيع الإعلانات، خصص رفًا للكتب التي يمكن استعارتها أسبوعًا مقابل تسجيل الاسم ووسيلة التواصل. بدأ بعشرين كتابًا من مجموعته الشخصية، واختار موضوعات متنوعة حتى يفهم ما يبحث عنه القراء.
في الأسابيع الأولى كانت الروايات أكثر الكتب استعارة، لكن دفاتر الملاحظات التي وضعها داخل الأغلفة كشفت أمرًا مختلفًا. فقد كتب عدد من القراء أنهم يريدون كتبًا عملية قصيرة عن الزراعة المنزلية وإصلاح الأشياء. أدرك سامي أن أرقام الاستعارة وحدها لا تشرح احتياجات الزوار كلها.
أضاف مجموعة صغيرة من الكتب العملية، ونظم لقاءً شهريًا يشرح فيه أحد القراء فكرة طبقها من كتاب. في اللقاء الأول عرضت معلمة طريقة بسيطة لتنظيم الوقت، وفي اللقاء الثاني أحضر شاب صندوقًا خشبيًا صنعه بالاستعانة بدليل مستعار. أصبحت اللقاءات فرصة لتبادل الخبرة، لا لمجرد الحديث عن العناوين.
بعد أربعة أشهر راجع سامي سجلات المكتبة. ارتفع عدد الزيارات، لكن بعض الكتب تأخر رجوعها. أرسل تذكيرات ودية وحدد موعد الإعادة بوضوح، دون إيقاف الاستعارة. وقرر إبقاء عدد الكتب محدودًا حتى يستطيع متابعة حالتها. بالنسبة إليه لم يكن النجاح في امتلاك رفوف أكثر، بل في وصول الكتاب المناسب إلى القارئ الذي سيستفيد منه.`,questions:[{q:'كم استمرت الاستعارة المسموح بها؟',options:['شهرًا','يومًا','أسبوعًا'],answer:2},{q:'ماذا كشفت ملاحظات القراء؟',options:['حاجتهم إلى كتب عملية قصيرة','رفضهم لكل الروايات','رغبتهم في إغلاق المكتبة'],answer:0},{q:'كيف تعامل سامي مع التأخر في الإعادة؟',options:['أوقف الاستعارة نهائيًا','أرسل تذكيرات وحدد الموعد','ضاعف عدد الرفوف'],answer:1}]},
{title:'الطريق إلى المدرسة',text:`كانت ليلى تصل إلى المدرسة متأخرة أحيانًا رغم خروجها من المنزل في الوقت نفسه. افترضت في البداية أن المسافة هي السبب، ثم قررت تسجيل تفاصيل رحلتها لمدة أسبوعين. كتبت وقت الخروج ووقت الوصول ومدة الانتظار عند التقاطعات، ولم تغيّر طريقها خلال فترة الملاحظة حتى تتمكن من المقارنة بصورة أوضح.
أظهرت الملاحظات أن معظم التأخير يحدث عند تقاطع واحد قرب السوق. كان الطريق الأقصر يمر بذلك التقاطع، بينما يوجد طريق آخر أطول قليلًا لكنه يحتوي على رصيف متصل ومعبر منظم. جربت ليلى الطريق البديل في الأسبوع التالي، فوجدت أن الوصول أصبح أكثر انتظامًا، حتى عندما لم تكن الرحلة أسرع بكثير.
عرضت نتائجها على زملائها في نشاط مدرسي عن الحي. اقترح بعضهم اختيار الطريق الأسرع في كل يوم، لكن المعلمة طلبت التفكير في الأمان وسهولة المشي أيضًا. اتفق الطلاب على أن قياس الزمن مهم، لكنه لا يكفي وحده للحكم على جودة الطريق. أضافوا إلى سجل الملاحظات أماكن الظل وحالة الأرصفة ووضوح إشارات العبور.
في نهاية النشاط أعد الفريق خريطة بسيطة توضح طريقين مناسبين، مع ملاحظات تساعد كل طالب على الاختيار بحسب موقع منزله. لم يعلنوا وجود طريق واحد مثالي للجميع. تعلمت ليلى أن الملاحظة المنتظمة قد تكشف سبب المشكلة، وأن الحل الجيد يوازن بين عدة عوامل بدلًا من تحسين رقم واحد وإهمال بقية التجربة.`,questions:[{q:'كم استمرت الملاحظة الأولى؟',options:['يومين','أسبوعين','شهرين'],answer:1},{q:'أين كان معظم التأخير؟',options:['عند تقاطع قرب السوق','داخل المدرسة','عند باب المنزل'],answer:0},{q:'ما خلاصة النشاط؟',options:['الطريق الأقصر هو الأفضل دائمًا','الزمن هو المعيار الوحيد','موازنة الزمن والأمان وسهولة المشي'],answer:2}]}
];
const storageKey='reading-speed-tests-v1';let results=[];try{results=JSON.parse(localStorage.getItem(storageKey))||[];if(!Array.isArray(results))results=[]}catch{}let selected,started=0,elapsed=0,phase='intro',interval;
const card=document.createElement('section');card.className='panel speed-card';card.innerHTML='<div class="heading"><h2>اختبر سرعة قراءتك</h2><span class="test-badge">كلمة / دقيقة</span></div><p id="lastTest" class="muted"></p><button id="startTest" class="space">ابدأ الاختبار</button>';$('view-home').insertBefore(card,$('view-home').querySelector('.overview'));
const historyPanel=document.createElement('section');historyPanel.className='panel';historyPanel.innerHTML='<h2>اختبارات القراءة</h2><div id="testHistory" class="history space"></div>';$('view-progress').append(historyPanel);
const dialog=document.createElement('dialog');dialog.id='speedDialog';dialog.className='speed-dialog';dialog.setAttribute('aria-labelledby','testTitle');dialog.innerHTML='<div class="heading"><h2 id="testTitle">اختبار سرعة القراءة</h2><button id="closeTest" class="secondary" aria-label="إغلاق الاختبار">×</button></div><div id="testBody"></div>';document.body.append(dialog);
function refresh(){const r=results.at(-1);$('lastTest').textContent=r?`آخر نتيجة: ${n(r.wpm)} كلمة/دقيقة · الفهم ${n(r.comprehension)}٪`:'اكتشف سرعتك بالكلمات في الدقيقة، مع قياس الفهم.';$('startTest').textContent=r?'أعد الاختبار':'ابدأ الاختبار';$('testHistory').replaceChildren();if(!results.length){$('testHistory').textContent='لم تُجرِ اختبارًا بعد.';return}const table=document.createElement('table');table.innerHTML='<thead><tr><th>التاريخ</th><th>كلمة/دقيقة</th><th>الفهم</th><th>مقارنة بالسابق</th></tr></thead>';const tbody=document.createElement('tbody');results.map((r,i)=>({r,i})).reverse().forEach(({r,i})=>{const prev=results[i-1],delta=prev?(r.wpm/prev.wpm-1)*100:null;const tr=document.createElement('tr');[new Date(r.date).toLocaleDateString('ar-SA',{calendar:'gregory'}),n(r.wpm),n(r.comprehension)+'٪',delta===null?'—':(delta>0?'+':'')+n(delta)+'٪'].forEach(t=>{const td=document.createElement('td');td.textContent=t;tr.append(td)});tbody.append(tr)});table.append(tbody);$('testHistory').append(table)}
function intro(){phase='intro';clearInterval(interval);const previous=results.at(-1);selected=previous?(previous.textIndex+1)%tests.length:0;const words=tests[selected].text.trim().split(/\s+/u).length;$('testBody').innerHTML=`<p>اقرأ النص مرة واحدة، ثم أجب عن ثلاثة أسئلة دون الرجوع إليه.</p><p class="muted space">${n(words)} كلمة · يتوقف احتساب الوقت عند إنهاء القراءة.</p><p class="muted space">النصوص متقاربة في الطول، لكنها ليست اختبارًا معياريًا. بعد ثلاثة اختبارات تتكرر النصوص وقد تؤثر الألفة بها في النتيجة.</p><button id="beginText" class="space">ابدأ القراءة الآن</button>`;$('beginText').onclick=read}
function read(){phase='reading';$('testBody').replaceChildren();const meta=document.createElement('p');meta.className='test-time muted';meta.id='testClock';meta.textContent='00:00';const heading=document.createElement('h3');heading.textContent=tests[selected].title;const passage=document.createElement('div');passage.className='test-passage';tests[selected].text.split('\n').forEach(t=>{const p=document.createElement('p');p.textContent=t;passage.append(p)});const end=document.createElement('button');end.id='endText';end.textContent='أنهيت القراءة';end.onclick=()=>{elapsed=(performance.now()-started)/1000;if(elapsed<1)return;clearInterval(interval);quiz()};$('testBody').append(meta,heading,passage,end);started=performance.now();interval=setInterval(()=>{const secs=Math.floor((performance.now()-started)/1000);if($('testClock'))$('testClock').textContent=String(Math.floor(secs/60)).padStart(2,'0')+':'+String(secs%60).padStart(2,'0')},500);dialog.scrollTop=0;end.focus({preventScroll:true})}
function quiz(){phase='quiz';$('testBody').innerHTML='<p class="muted">اختر الإجابة الصحيحة لكل سؤال.</p><form id="quizForm"></form>';const form=$('quizForm');tests[selected].questions.forEach((q,i)=>{const field=document.createElement('fieldset'),legend=document.createElement('legend');legend.textContent=q.q;field.append(legend);q.options.forEach((text,j)=>{const label=document.createElement('label'),input=document.createElement('input');input.type='radio';input.name='q'+i;input.value=j;input.required=true;label.append(input,document.createTextNode(text));field.append(label)});form.append(field)});const btn=document.createElement('button');btn.textContent='عرض النتيجة';form.append(btn);form.onsubmit=e=>{e.preventDefault();if(phase!=='quiz')return;const data=new FormData(form),correct=tests[selected].questions.filter((q,i)=>Number(data.get('q'+i))===q.answer).length,words=tests[selected].text.trim().split(/\s+/u).length;const r={id:crypto.randomUUID(),date:new Date().toISOString(),textIndex:selected,words,seconds:elapsed,wpm:Math.round(words*60/elapsed),comprehension:Math.round(correct/3*100)};let saved=true;try{localStorage.setItem(storageKey,JSON.stringify([...results,r]));results.push(r)}catch{saved=false}phase='result';$('testBody').innerHTML=`<div class="test-results"><div><strong>${n(r.wpm)}</strong><span>كلمة / دقيقة</span></div><div><strong>${n(r.comprehension)}٪</strong><span>الفهم · ${n(correct)} من ٣</span></div></div><p class="muted space">${n(words)} كلمة خلال ${n(elapsed/60)} دقيقة. وقت الإجابة عن الأسئلة غير محسوب.</p><p class="muted space">${saved?'حُفظت النتيجة في تقدمي.':'تعذّر حفظ النتيجة في المتصفح.'}</p><button id="finishTest" class="space">تم</button>`;$('finishTest').onclick=()=>dialog.close();refresh();dialog.scrollTop=0};dialog.scrollTop=0}
function close(){if(phase==='reading'||phase==='quiz'){phase='interrupted';clearInterval(interval);$('testBody').innerHTML='<p>لم يُحفظ الاختبار غير المكتمل.</p><button id="exitTest" class="space">إغلاق</button>';$('exitTest').onclick=()=>dialog.close()}else dialog.close()}
$('closeTest').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&phase==='reading'&&dialog.open){clearInterval(interval);phase='interrupted';$('testBody').innerHTML='<p>توقف الاختبار عند مغادرة الصفحة لضمان دقة الوقت. يمكنك البدء من جديد.</p><button id="restartTest" class="space">إعادة الاختبار</button>';$('restartTest').onclick=intro}});$('startTest').onclick=()=>{intro();dialog.showModal()};refresh();
})();
