'use strict';
let currentView='home';const viewTitles={home:'الرئيسية',books:'كتبي',reader:'جلستي',progress:'تقدمي'};
function go(view,focus=true){if(!viewTitles[view])view='home';currentView=view;document.querySelectorAll('.app-view').forEach(el=>el.hidden=el.id!=='view-'+view);document.querySelectorAll('[data-view]').forEach(el=>{if(el.dataset.view===view)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')});$('screenTitle').textContent=viewTitles[view];if(location.hash!=='#'+view)history.replaceState(null,'','#'+view);refreshUI();if(focus){window.scrollTo({top:0,behavior:'instant'});$('screenTitle').focus({preventScroll:true})}}
const dayIndex=()=>Math.max(0,Math.min(20,Math.floor((new Date(today()+'T12:00:00')-new Date(state.start+'T12:00:00'))/86400000)));
function editBook(i){state.selected=i;save();render();$('bookDialog').showModal()}
function refreshUI(){const i=dayIndex(),b=state.books[i],p=pagesFor(i);$('todayLabel').textContent='اليوم '+n(i+1)+' من ٢١';$('todayBook').textContent=b.title||'اختر كتابك لهذا اليوم';$('todayAuthor').textContent=b.author||'كل جلسة تقرّبك من إنجاز كتابك.';$('todayProgress').textContent=b.total?`${n(p)} من ${n(b.total)} صفحة · ${n(Math.min(100,p/b.total*100))}٪`:'أضف عنوان الكتاب وعدد صفحاته للبدء.';$('todayBar').style.width=(b.total?Math.min(100,p/b.total*100):0)+'%';$('todayRead').textContent=state.timer?'العودة إلى الجلسة':b.total?'ابدأ القراءة':'أضف كتاب اليوم';
$('bookList').replaceChildren();state.books.forEach((book,index)=>{const btn=document.createElement('button');btn.className='book-tile'+(index===state.selected?' selected':'');btn.setAttribute('aria-pressed',String(index===state.selected));const day=document.createElement('small');day.textContent='اليوم '+n(index+1);const name=document.createElement('strong');name.textContent=book.title||'إضافة كتاب';const status=document.createElement('small');const read=pagesFor(index);status.textContent=book.total?(read>=book.total?'مكتمل':`${n(read)} / ${n(book.total)} صفحة`):'لم تُضف بياناته';const bar=document.createElement('div');bar.className='bar';const fill=document.createElement('span');fill.style.width=(book.total?Math.min(100,read/book.total*100):0)+'%';bar.append(fill);btn.append(day,name,status,bar);btn.onclick=()=>{state.selected=index;save();render();if(!book.total)editBook(index)};$('bookList').append(btn)});
$('readerSelect').replaceChildren();state.books.forEach((book,index)=>{if(book.total){const option=document.createElement('option');option.value=index;option.textContent=book.title+(pagesFor(index)>=book.total?' — مكتمل':'');$('readerSelect').append(option)}});if(!$('readerSelect').options.length){const option=document.createElement('option');option.textContent='أضف كتابًا من شاشة كتبي';option.value='';$('readerSelect').append(option)}$('readerSelect').value=String(state.timer?state.timer.book:state.selected);$('readerSelect').disabled=!!state.timer;$('readerHint').textContent=state.timer?'أنه الجلسة الحالية قبل الانتقال إلى كتاب آخر.':'اختر كتابًا ثم ابدأ المؤقّت، أو أضف جلسة سابقة.';$('miniTimer').hidden=!state.timer||currentView==='reader';if(state.timer){$('miniBook').textContent=state.books[state.timer.book].title;$('miniPause').textContent=state.timer.running?'إيقاف':'استئناف';$('miniPause').setAttribute('aria-label',state.timer.running?'إيقاف المؤقّت':'استئناف المؤقّت')}$('miniClock').textContent=$('clock').textContent;}
const originalRender=render;render=function(){originalRender();refreshUI()};const originalClock=updateClock;updateClock=function(){originalClock();$('miniClock').textContent=$('clock').textContent};
document.querySelectorAll('[data-view]').forEach(btn=>btn.onclick=()=>go(btn.dataset.view));document.querySelectorAll('[data-go]').forEach(btn=>btn.onclick=()=>go(btn.dataset.go));window.addEventListener('hashchange',()=>go(location.hash.slice(1)));
$('todayEdit').onclick=()=>editBook(dayIndex());$('todayRead').onclick=()=>{if(state.timer){go('reader');return}const i=dayIndex();if(!state.books[i].total){editBook(i);return}state.selected=i;save();render();go('reader')};$('editBook').onclick=()=>editBook(state.selected);$('readBook').onclick=()=>{if(!state.books[state.selected].total){editBook(state.selected);return}go('reader')};$('closeBook').onclick=()=>$('bookDialog').close();$('bookForm').addEventListener('submit',()=>{if(state.books[state.selected].title===$('title').value.trim()&&state.books[state.selected].total===Number($('total').value))$('bookDialog').close()});$('readerSelect').onchange=()=>{if(!state.timer&&$('readerSelect').value!==''){state.selected=Number($('readerSelect').value);save();render()}};$('miniOpen').onclick=()=>go('reader');$('miniPause').onclick=()=>$('play').click();
let installPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});$('install').onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null}else{notice('لتثبيت التطبيق: افتح قائمة المتصفح واختر «إضافة إلى الشاشة الرئيسية». على iPhone استخدم زر المشاركة في Safari.')}};window.addEventListener('appinstalled',()=>{$('install').hidden=true;notice('تم تثبيت التطبيق')});if(matchMedia('(display-mode: standalone)').matches||navigator.standalone)$('install').hidden=true;
if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
const home=$('view-home');home.insertBefore(home.querySelector('.today-card'),home.querySelector('.overview'));
go(location.hash.slice(1)||'home',false);
setInterval(()=>{$('miniClock').textContent=$('clock').textContent},1000);
